bipartite:
  bipartite/atac_rna:
    graph_type: '00'
    source: RNA
    target: peaks
  bipartite/tf_peak:
    graph_type: '00'
    source: peaks
    target: TF_network
multiplex:
  RNA:
    graph_type:
    - '10'
    layers:
    - multiplex/RNA/RNA_GENIE3.tsv
  TF:
    graph_type:
    - '00'
    layers:
    - multiplex/TF/TF_network.tsv
  peaks:
    graph_type:
    - '10'
    layers:
    - multiplex/peaks/peak_network_cicero.tsv
r: 0.7
seed: seeds/seeds.txt
self_loops: 0
