bipartite:
  bipartite/atac_rna:
    graph_type: '00'
    source: RNA
    target: peaks
  bipartite/tf_peaks:
    graph_type: '00'
    source: peaks
    target: TF_network
eta:
- 0.0
- 1.0
- 0.0
lambda:
- - 0.3333333333333333
  - 0.3333333333333333
  - 0.3333333333333333
- - 1/3
  - 1/3
  - 1/3
- - 1/3
  - 1/3
  - 1/3
multiplex:
  RNA:
    graph_type: '00'
    layers:
    - multiplex/RNA/R
    - multiplex/RNA/N
    - multiplex/RNA/A
    - multiplex/RNA/_
    - multiplex/RNA/G
    - multiplex/RNA/E
    - multiplex/RNA/N
    - multiplex/RNA/I
    - multiplex/RNA/E
    - multiplex/RNA/3
r: 0.7
seed: seeds/seeds.txt
self_loops: 0
