bipartite:
  bipartite/atac_rna:
    graph_type: '00'
    source: RNA
    target: peaks
  bipartite/tf_peak:
    graph_type: '00'
    source: peaks
    target: TF_network
eta: null
lambda: null
multiplex:
  RNA:
    graph_type: '00'
    layers:
    - multiplex/RNA/R
    - multiplex/RNA/N
    - multiplex/RNA/A
    - multiplex/RNA/_
    - multiplex/RNA/G
    - multiplex/RNA/E
    - multiplex/RNA/N
    - multiplex/RNA/I
    - multiplex/RNA/E
    - multiplex/RNA/3
  TF:
    graph_type: '00'
    layers:
    - multiplex/TF/T
    - multiplex/TF/F
    - multiplex/TF/_
    - multiplex/TF/n
    - multiplex/TF/e
    - multiplex/TF/t
    - multiplex/TF/w
    - multiplex/TF/o
    - multiplex/TF/r
    - multiplex/TF/k
  peaks:
    graph_type: '10'
    layers:
    - multiplex/peaks/p
    - multiplex/peaks/e
    - multiplex/peaks/a
    - multiplex/peaks/k
    - multiplex/peaks/_
    - multiplex/peaks/n
    - multiplex/peaks/e
    - multiplex/peaks/t
    - multiplex/peaks/w
    - multiplex/peaks/o
    - multiplex/peaks/r
    - multiplex/peaks/k
    - multiplex/peaks/_
    - multiplex/peaks/c
    - multiplex/peaks/i
    - multiplex/peaks/c
    - multiplex/peaks/e
    - multiplex/peaks/r
    - multiplex/peaks/o
r: 0.7
seed: seeds/seeds.txt
self_loops: 0
